# Generated by Django 5.1 on 2024-10-01 13:11

import django.db.models.deletion
import groups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='group_owner',
            field=models.ForeignKey(default=groups.models.get_system_admin, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owned_groups', to=settings.AUTH_USER_MODEL, verbose_name='Group Owner'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='members',
            field=models.ManyToManyField(related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
