# Generated by Django 5.1 on 2024-09-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='This Is A Quiz', verbose_name='Quiz_Description'),
        ),
    ]
