# Generated by Django 5.1 on 2024-09-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_quiztaker_quiz_taken_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztaker',
            options={'ordering': ['completed_at']},
        ),
    ]
