# Generated by Django 5.1 on 2024-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quiztaker_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
